//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elev
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Elev()
        {
            this.KursBetyg = new HashSet<KursBetyg>();
        }
    
        public string Personnummer { get; set; }
        public string Fornamn { get; set; }
        public string Efternamn { get; set; }
        public string Epost { get; set; }
        public string Telefon { get; set; }
        public string Klasskod { get; set; }
        public string Ort { get; set; }
    
        public virtual Klass Klass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KursBetyg> KursBetyg { get; set; }
    }
}
