//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class KursBetyg
    {
        public string Personnummer { get; set; }
        public string Kurskod { get; set; }
        public string Betyg { get; set; }
    
        public virtual BetygVarde BetygVarde { get; set; }
        public virtual Elev Elev { get; set; }
        public virtual Kurs Kurs { get; set; }
    }
}
