//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Larare
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Larare()
        {
            this.Kurs = new HashSet<Kurs>();
        }
    
        public int Anstallningsnummer { get; set; }
        public string Fornamn { get; set; }
        public string Efternamn { get; set; }
        public string Epost { get; set; }
        public string Telefon { get; set; }
        public Nullable<int> Avdelningsnummer { get; set; }
        public string Ort { get; set; }
        public Nullable<int> Lon { get; set; }
    
        public virtual Avdelning Avdelning { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kurs> Kurs { get; set; }
    }
}
