//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SkolaEntities : DbContext
    {
        public SkolaEntities()
            : base("name=SkolaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Avdelning> Avdelning { get; set; }
        public virtual DbSet<BetygConvert> BetygConvert { get; set; }
        public virtual DbSet<BetygVarde> BetygVarde { get; set; }
        public virtual DbSet<Elev> Elev { get; set; }
        public virtual DbSet<Klass> Klass { get; set; }
        public virtual DbSet<Kurs> Kurs { get; set; }
        public virtual DbSet<KursBetyg> KursBetyg { get; set; }
        public virtual DbSet<KursLokal> KursLokal { get; set; }
        public virtual DbSet<Larare> Larare { get; set; }
        public virtual DbSet<Lokal> Lokal { get; set; }
        public virtual DbSet<TidigareElev> TidigareElev { get; set; }
    }
}
